# Generated by Django 4.1 on 2023-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.png", null=True, upload_to=""),
        ),
    ]
